import { defineCollection } from 'astro:content';
import { glob, file } from 'astro/loaders';
import { z } from 'astro/zod';

const lessons = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/lessons' }),
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    section: z.string().default('tutorials'),
    order: z.number().optional(),
    description: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

const resources = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/resources' }),
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    source: z.enum(['arena', 'github', 'zotero', 'manual']),
    description: z.string().optional(),
    heroImage: z.string().optional(),
    lastFetched: z.string().optional(),
    arenaId: z.number().optional(),
    blockCount: z.number().optional(),
    tags: z.array(z.string()).default([]),
  }),
});

/* Zotero bibliography lives as a single JSON file generated by
   scripts/fetch-zotero.ts. The `file()` loader treats each element of the
   parsed array as one collection entry. The parser handles two cases:
   - The expected `{ entries: [...] }` shape from a successful fetch
   - File missing or malformed → return an empty array so the build doesn't
     crash before the user has run `npm run build:resources`. */
const bibliography = defineCollection({
  loader: file('src/data/zotero.json', {
    parser: (text: string) => {
      try {
        const data = JSON.parse(text);
        if (Array.isArray(data?.entries)) {
          // file() expects each entry to have an `id` field for collection lookup.
          return data.entries.map((e: { key: string }) => ({ ...e, id: e.key }));
        }
      } catch {
        /* fall through to empty */
      }
      return [];
    },
  }),
  schema: z.object({
    key: z.string(),
    type: z.string(),
    title: z.string(),
    url: z.string().optional(),
    doi: z.string().optional(),
    date: z.string().optional(),
    year: z.number().optional(),
    tags: z.array(z.string()).default([]),
    /** Keys of Zotero sub-collections this entry belongs to (top-level
        groupings on the bibliography page). */
    subcollections: z.array(z.string()).default([]),
    csl: z.unknown(),
    bib: z.string(),
    bibtex: z.string(),
  }),
});

export const collections = { lessons, resources, bibliography };
